name: release package

on: workflow_dispatch

jobs:
  release-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run: npm ci

      - name: set commit bot
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
        
      - name: bump conventional commits
        run: npx lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: release new version to npmjs
        run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
